import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  backText: { fontSize: 16, color: '#7F77DD', fontWeight: '600' },
  title: { fontSize: 18, fontWeight: '600', color: '#1a1a1a' },
  editText: { fontSize: 16, color: '#7F77DD', fontWeight: '600' },
  content: { flex: 1, padding: 16 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  statusBadge: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, marginBottom: 16 },
  statusText: { fontSize: 13, color: '#1a1a1a', fontWeight: '600' },
  section: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: '600', color: '#999', marginBottom: 8 },
  postContent: { fontSize: 16, color: '#333', lineHeight: 24 },
  meta: { fontSize: 12, color: '#777', marginTop: 6 },
  platformList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  platformBadge: { backgroundColor: '#f0f0f0', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  platformBadgeText: { fontSize: 13, color: '#666' },
  analyticsRow: { marginBottom: 12 },
  analyticsPlatform: { fontSize: 13, fontWeight: '600', color: '#333', marginBottom: 6 },
  metricsRow: { flexDirection: 'row', gap: 12 },
  metricItem: { flex: 1, alignItems: 'center' },
  metricValue: { fontSize: 18, fontWeight: '700', color: '#7F77DD' },
  metricLabel: { fontSize: 11, color: '#999', marginTop: 2 },
  actions: { flexDirection: 'row', gap: 12, marginBottom: 32 },
  actionButton: { flex: 1, borderWidth: 1, borderColor: '#7F77DD', borderRadius: 12, padding: 14, alignItems: 'center' },
  actionButtonText: { color: '#7F77DD', fontSize: 15, fontWeight: '600' },
  deleteButton: { borderColor: '#F44336' },
  deleteButtonText: { color: '#F44336', fontSize: 15, fontWeight: '600' },
  errorText: { color: '#F44336', marginBottom: 8, paddingHorizontal: 32, textAlign: 'center' },
  retryBtn: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#7F77DD', borderRadius: 6 },
  retryText: { color: '#fff', fontWeight: '600' },
});
