export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',

  PLAN_LIMIT_POSTS: 'PLAN_LIMIT_POSTS',
  PLAN_LIMIT_ACCOUNTS: 'PLAN_LIMIT_ACCOUNTS',
  PLAN_LIMIT_SEATS: 'PLAN_LIMIT_SEATS',
  PLAN_LIMIT_PROJECTS: 'PLAN_LIMIT_PROJECTS',
  PLAN_LIMIT_STORAGE: 'PLAN_LIMIT_STORAGE',
  PLAN_LIMIT_AI_CREDITS: 'PLAN_LIMIT_AI_CREDITS',
  PLAN_LIMIT_SCHEDULED_QUEUE: 'PLAN_LIMIT_SCHEDULED_QUEUE',
  PLAN_FEATURE_DISABLED: 'PLAN_FEATURE_DISABLED',

  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',
  WORKSPACE_MEMBER_EXISTS: 'WORKSPACE_MEMBER_EXISTS',

  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ALREADY_PUBLISHED: 'POST_ALREADY_PUBLISHED',
  POST_VALIDATION_FAILED: 'POST_VALIDATION_FAILED',
  POST_PUBLISHING_FAILED: 'POST_PUBLISHING_FAILED',

  SOCIAL_ACCOUNT_NOT_FOUND: 'SOCIAL_ACCOUNT_NOT_FOUND',
  SOCIAL_TOKEN_EXPIRED: 'SOCIAL_TOKEN_EXPIRED',
  SOCIAL_TOKEN_REFRESH_FAILED: 'SOCIAL_TOKEN_REFRESH_FAILED',
  SOCIAL_API_ERROR: 'SOCIAL_API_ERROR',

  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_FILE_TOO_LARGE: 'MEDIA_FILE_TOO_LARGE',
  MEDIA_INVALID_TYPE: 'MEDIA_INVALID_TYPE',
  MEDIA_STORAGE_EXCEEDED: 'MEDIA_STORAGE_EXCEEDED',

  BILLING_PAYMENT_FAILED: 'BILLING_PAYMENT_FAILED',
  BILLING_SUBSCRIPTION_INACTIVE: 'BILLING_SUBSCRIPTION_INACTIVE',
  BILLING_WEBHOOK_INVALID: 'BILLING_WEBHOOK_INVALID',

  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
