import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const plans = [
  {
    name: 'Free',
    slug: 'free',
    description: 'Get started with basic social media management',
    price_monthly_usd: 0,
    price_annual_usd: 0,
    seat_price_usd: 0,
    is_active: true,
    is_custom: false,
    sort_order: 0,
    limits: {
      posts_per_month: 4,
      connected_accounts: 2,
      analytics_days: 7,
      team_members: 1,
      projects: 0,
      max_scheduled_queue: 0,
      storage_gb: 0.5,
      ai_credits: 0,
      rate_limit_per_hour: null,
    },
    features: {
      scheduling: false,
      platform_previews: false,
      mention_tagging: false,
      best_time_suggestions: false,
      approval_workflows: false,
      white_label_reports: false,
      bulk_csv_scheduling: false,
      client_portal: false,
      client_invoicing: false,
      webhooks: false,
      api_access: false,
      custom_bio_domain: false,
      white_label_app: false,
      sla_guarantee: false,
    },
  },
  {
    name: 'Starter',
    slug: 'starter',
    description: 'For creators ready to grow their social presence',
    price_monthly_usd: 9,
    price_annual_usd: 84,
    seat_price_usd: 0,
    is_active: true,
    is_custom: false,
    sort_order: 1,
    limits: {
      posts_per_month: 30,
      connected_accounts: 3,
      analytics_days: 30,
      team_members: 1,
      projects: 0,
      max_scheduled_queue: 50,
      storage_gb: 2,
      ai_credits: 20,
      rate_limit_per_hour: null,
    },
    features: {
      scheduling: true,
      platform_previews: true,
      mention_tagging: false,
      best_time_suggestions: false,
      approval_workflows: false,
      white_label_reports: false,
      bulk_csv_scheduling: false,
      client_portal: false,
      client_invoicing: false,
      webhooks: false,
      api_access: false,
      custom_bio_domain: false,
      white_label_app: false,
      sla_guarantee: false,
    },
  },
  {
    name: 'Pro',
    slug: 'pro',
    description: 'For professionals and growing brands',
    price_monthly_usd: 19,
    price_annual_usd: 180,
    seat_price_usd: 0,
    is_active: true,
    is_custom: false,
    sort_order: 2,
    limits: {
      posts_per_month: 200,
      connected_accounts: 6,
      analytics_days: 90,
      team_members: 1,
      projects: 0,
      max_scheduled_queue: 200,
      storage_gb: 10,
      ai_credits: 100,
      rate_limit_per_hour: null,
    },
    features: {
      scheduling: true,
      platform_previews: true,
      mention_tagging: true,
      best_time_suggestions: true,
      approval_workflows: false,
      white_label_reports: false,
      bulk_csv_scheduling: false,
      client_portal: false,
      client_invoicing: false,
      webhooks: false,
      api_access: false,
      custom_bio_domain: true,
      white_label_app: false,
      sla_guarantee: false,
    },
  },
  {
    name: 'Enterprise',
    slug: 'enterprise',
    description: 'For agencies and large teams',
    price_monthly_usd: 79,
    price_annual_usd: 756,
    seat_price_usd: 15,
    is_active: true,
    is_custom: false,
    sort_order: 3,
    limits: {
      posts_per_month: 500,
      connected_accounts: 20,
      analytics_days: 365,
      team_members: 5,
      projects: 10,
      max_scheduled_queue: 500,
      storage_gb: 50,
      ai_credits: 500,
      rate_limit_per_hour: null,
    },
    features: {
      scheduling: true,
      platform_previews: true,
      mention_tagging: true,
      best_time_suggestions: true,
      approval_workflows: true,
      white_label_reports: true,
      bulk_csv_scheduling: true,
      client_portal: true,
      client_invoicing: true,
      webhooks: true,
      api_access: false,
      custom_bio_domain: true,
      white_label_app: false,
      sla_guarantee: false,
    },
  },
  {
    name: 'Custom',
    slug: 'custom',
    description: 'Tailored solution for enterprise needs',
    price_monthly_usd: 0,
    price_annual_usd: 0,
    seat_price_usd: 0,
    is_active: true,
    is_custom: true,
    sort_order: 4,
    limits: {
      posts_per_month: -1,
      connected_accounts: -1,
      analytics_days: -1,
      team_members: -1,
      projects: -1,
      max_scheduled_queue: -1,
      storage_gb: -1,
      ai_credits: -1,
      rate_limit_per_hour: 10000,
    },
    features: {
      scheduling: true,
      platform_previews: true,
      mention_tagging: true,
      best_time_suggestions: true,
      approval_workflows: true,
      white_label_reports: true,
      bulk_csv_scheduling: true,
      client_portal: true,
      client_invoicing: true,
      webhooks: true,
      api_access: true,
      custom_bio_domain: true,
      white_label_app: true,
      sla_guarantee: true,
    },
  },
];

async function seedPlans() {
  for (const plan of plans) {
    await prisma.plan.upsert({
      where: { slug: plan.slug },
      update: {
        name: plan.name,
        description: plan.description,
        price_monthly_usd: plan.price_monthly_usd,
        price_annual_usd: plan.price_annual_usd,
        seat_price_usd: plan.seat_price_usd,
        limits: plan.limits,
        features: plan.features,
        is_active: plan.is_active,
        is_custom: plan.is_custom,
        sort_order: plan.sort_order,
      },
      create: plan,
    });
  }
  console.log(`Seeded ${plans.length} plans`);
}

seedPlans()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
