import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const platforms = [
  {
    slug: 'facebook',
    name: 'Facebook',
    display_name: 'Facebook',
    color: '#1877F2',
    api_version: 'Graph API v21',
    auth_type: 'oauth2',
    phase: 1,
    max_caption_chars: 63206,
    max_images: 10,
    max_file_size_mb: 4096,
    max_video_duration_sec: 14400,
    min_image_width: 200,
    min_image_height: 200,
    is_active: true,
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    display_name: 'Instagram',
    color: '#E4405F',
    api_version: 'Graph API v21',
    auth_type: 'oauth2',
    phase: 1,
    max_caption_chars: 2200,
    max_images: 10,
    max_file_size_mb: 4096,
    max_video_duration_sec: 5400,
    min_image_width: 320,
    min_image_height: 320,
    is_active: true,
  },
  {
    slug: 'x',
    name: 'X',
    display_name: 'X / Twitter',
    color: '#000000',
    api_version: 'API v2',
    auth_type: 'oauth2_pkce',
    phase: 1,
    max_caption_chars: 280,
    max_images: 4,
    max_file_size_mb: 512,
    max_video_duration_sec: 140,
    min_image_width: 200,
    min_image_height: 200,
    is_active: true,
  },
  {
    slug: 'linkedin',
    name: 'LinkedIn',
    display_name: 'LinkedIn',
    color: '#0A66C2',
    api_version: 'UGC Posts API v2',
    auth_type: 'oauth2',
    phase: 1,
    max_caption_chars: 3000,
    max_images: 9,
    max_file_size_mb: 5120,
    max_video_duration_sec: 600,
    min_image_width: 552,
    min_image_height: 276,
    is_active: true,
  },
  {
    slug: 'tiktok',
    name: 'TikTok',
    display_name: 'TikTok',
    color: '#000000',
    api_version: 'Content Posting API',
    auth_type: 'oauth2',
    phase: 1,
    max_caption_chars: 2200,
    max_images: 35,
    max_file_size_mb: 4096,
    max_video_duration_sec: 600,
    min_image_width: 360,
    min_image_height: 640,
    is_active: true,
  },
  {
    slug: 'google_business',
    name: 'Google Business',
    display_name: 'Google Business Profile',
    color: '#4285F4',
    api_version: 'My Business API v4.9',
    auth_type: 'oauth2',
    phase: 1,
    max_caption_chars: 1500,
    max_images: 1,
    max_file_size_mb: 25,
    max_video_duration_sec: 0,
    min_image_width: 250,
    min_image_height: 250,
    is_active: true,
  },
  {
    slug: 'pinterest',
    name: 'Pinterest',
    display_name: 'Pinterest',
    color: '#BD081C',
    api_version: 'API v5',
    auth_type: 'oauth2',
    phase: 2,
    max_caption_chars: 500,
    max_images: 1,
    max_file_size_mb: 32,
    max_video_duration_sec: 900,
    min_image_width: 236,
    min_image_height: 354,
    is_active: true,
  },
  {
    slug: 'youtube',
    name: 'YouTube',
    display_name: 'YouTube',
    color: '#FF0000',
    api_version: 'Data API v3',
    auth_type: 'oauth2',
    phase: 2,
    max_caption_chars: 5000,
    max_images: 0,
    max_file_size_mb: 262144,
    max_video_duration_sec: 43200,
    min_image_width: 0,
    min_image_height: 0,
    is_active: true,
  },
  {
    slug: 'whatsapp',
    name: 'WhatsApp',
    display_name: 'WhatsApp Business',
    color: '#25D366',
    api_version: 'Business Cloud API',
    auth_type: 'system_user_token',
    phase: 2,
    max_caption_chars: 4096,
    max_images: 1,
    max_file_size_mb: 100,
    max_video_duration_sec: 120,
    min_image_width: 0,
    min_image_height: 0,
    is_active: true,
  },
  {
    slug: 'threads',
    name: 'Threads',
    display_name: 'Threads',
    color: '#000000',
    api_version: 'Threads API (Meta)',
    auth_type: 'oauth2',
    phase: 2,
    max_caption_chars: 500,
    max_images: 20,
    max_file_size_mb: 1024,
    max_video_duration_sec: 300,
    min_image_width: 320,
    min_image_height: 320,
    is_active: true,
  },
];

async function seedPlatforms() {
  for (const platform of platforms) {
    await prisma.platform.upsert({
      where: { slug: platform.slug },
      update: platform,
      create: platform,
    });
  }
  console.log(`Seeded ${platforms.length} platforms`);
}

seedPlatforms()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
