import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  header: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: 20, paddingVertical: 16, backgroundColor: '#fff',
    borderBottomWidth: 1, borderBottomColor: '#eee',
  },
  backText: { fontSize: 16, color: '#7F77DD', fontWeight: '600' },
  title: { fontSize: 18, fontWeight: '600', color: '#1a1a1a' },
  content: { flex: 1, padding: 16 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  currentPlan: { backgroundColor: '#7F77DD', borderRadius: 12, padding: 24, alignItems: 'center', marginBottom: 16 },
  planLabel: { fontSize: 14, color: 'rgba(255,255,255,0.7)', marginBottom: 4 },
  planName: { fontSize: 28, fontWeight: '700', color: '#fff', marginBottom: 4 },
  planPrice: { fontSize: 16, color: 'rgba(255,255,255,0.9)' },
  planStatus: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 6 },
  upgradeButton: { backgroundColor: '#7F77DD', borderRadius: 12, padding: 16, alignItems: 'center', marginBottom: 16 },
  upgradeButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  section: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#1a1a1a', marginBottom: 12 },
  emptyState: { alignItems: 'center', paddingVertical: 20 },
  emptyText: { fontSize: 14, color: '#999' },
  historyRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  historyPlan: { fontSize: 15, fontWeight: '600', color: '#1a1a1a' },
  historyDate: { fontSize: 12, color: '#999', marginTop: 2 },
  historyAmount: { fontSize: 15, fontWeight: '600', color: '#1a1a1a' },
  historyStatus: { fontSize: 12, color: '#999', marginTop: 2, textTransform: 'capitalize' },
});
