import type { Metadata } from 'next';

interface ReportRenderPageProps {
  params: Promise<{ jobId: string }>;
}

export async function generateMetadata({ params }: ReportRenderPageProps): Promise<Metadata> {
  const { jobId } = await params;
  return { title: `Report Render - ${jobId}` };
}

export default async function ReportRenderPage({ params }: ReportRenderPageProps) {
  const { jobId } = await params;

  return (
    <div className="min-h-screen bg-white p-8">
      <div className="mx-auto max-w-4xl">
        <header className="border-b pb-6">
          <h1 className="font-heading text-3xl font-bold">Social Media Performance Report</h1>
          <p className="mt-2 text-sm text-gray-500">
            Generated for job: {jobId} &middot; Report Date: March 2026
          </p>
        </header>

        <section className="mt-8">
          <h2 className="font-heading text-xl font-bold">Executive Summary</h2>
          <div className="mt-4 grid grid-cols-4 gap-4">
            {[
              { label: 'Total Reach', value: '245,000' },
              { label: 'Engagements', value: '12,400' },
              { label: 'Followers Gained', value: '+2,100' },
              { label: 'Posts Published', value: '86' },
            ].map((metric) => (
              <div key={metric.label} className="rounded border p-4 text-center">
                <p className="text-xs text-gray-500">{metric.label}</p>
                <p className="mt-1 text-xl font-bold">{metric.value}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-8">
          <h2 className="font-heading text-xl font-bold">Platform Breakdown</h2>
          <div className="mt-4 h-64 rounded border border-dashed border-gray-300 flex items-center justify-center text-sm text-gray-400">
            Platform performance chart renders here for PDF export.
          </div>
        </section>

        <section className="mt-8">
          <h2 className="font-heading text-xl font-bold">Top Performing Posts</h2>
          <div className="mt-4 space-y-3">
            {[1, 2, 3].map((i) => (
              <div key={i} className="rounded border p-4">
                <p className="text-sm text-gray-700">Top performing post #{i} content preview...</p>
                <div className="mt-2 flex gap-4 text-xs text-gray-500">
                  <span>Impressions: {(5000 - i * 500).toLocaleString()}</span>
                  <span>Engagements: {(800 - i * 100).toLocaleString()}</span>
                  <span>Clicks: {(200 - i * 30).toLocaleString()}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        <footer className="mt-12 border-t pt-6 text-center text-xs text-gray-400">
          Report generated by myManager &middot; {new Date().toISOString().split('T')[0]}
        </footer>
      </div>
    </div>
  );
}
